#!/usr/bin/env bash
# amux uninstaller — the inverse of ./install.sh.
#
# Removes: the launchd agents (server + builder) and the installed binaries.
# NEVER touches ~/.amux — your DB, sessions, tokens, memory and logs are
# data, and an uninstaller that deletes data is a bug, not a feature.
# Re-running ./install.sh against the same AMUX_HOME picks all of it back up.
#
# Honors the same overrides as install.sh (AMUX_INSTALL_BIN,
# AMUX_LAUNCHD_LABEL, AMUX_LAUNCHD_DIR, AMUX_HOME — the last only to NAME
# what is being kept).
set -euo pipefail

BOLD=$'\033[1m' GREEN=$'\033[32m' YELLOW=$'\033[33m' RESET=$'\033[0m'
say()  { echo "${GREEN}✓${RESET} $*"; }
warn() { echo "${YELLOW}!${RESET} $*"; }

AMUX_HOME="${AMUX_HOME:-$HOME/.amux}"
BIN_DIR="${AMUX_INSTALL_BIN:-$HOME/.local/bin}"
LABEL="${AMUX_LAUNCHD_LABEL:-com.amux.server-rs}"
PLIST_DIR="${AMUX_LAUNCHD_DIR:-$HOME/Library/LaunchAgents}"
UID_N="$(id -u)"

echo "${BOLD}amux uninstaller${RESET}"
echo ""

if [[ "$(uname -s)" == "Darwin" ]]; then
  for l in "$LABEL-builder" "$LABEL"; do
    if launchctl print "gui/$UID_N/$l" >/dev/null 2>&1; then
      launchctl bootout "gui/$UID_N/$l" 2>/dev/null || true
      say "stopped + unloaded launchd agent: $l"
    fi
    if [[ -f "$PLIST_DIR/$l.plist" ]]; then
      rm -f "$PLIST_DIR/$l.plist"
      say "removed $PLIST_DIR/$l.plist"
    fi
  done
fi

# Linux: the systemd user units install.sh writes. Without this the uninstaller
# left every unit behind, so the server came back on the next boot or timer
# tick — an uninstall that does not uninstall.
if [[ "$(uname -s)" != "Darwin" ]] && command -v systemctl >/dev/null 2>&1; then
  SYSTEMD_DIR="${AMUX_SYSTEMD_DIR:-$HOME/.config/systemd/user}"
  for u in amux-server.service amux-builder.timer amux-builder.service \
           amux-worker-start.service amux-xvfb.service; do
    if systemctl --user is-active --quiet "$u" 2>/dev/null; then
      systemctl --user stop "$u" 2>/dev/null || true
      say "stopped $u"
    fi
    systemctl --user disable "$u" >/dev/null 2>&1 || true
    if [[ -f "$SYSTEMD_DIR/$u" ]]; then
      rm -f "$SYSTEMD_DIR/$u"
      say "removed $SYSTEMD_DIR/$u"
    fi
  done
  # Template unit + any instances enabled from it.
  for inst in "$SYSTEMD_DIR"/amux-playwright-mcp@*.service; do
    [[ -e "$inst" ]] || continue
    systemctl --user stop "$(basename "$inst")" 2>/dev/null || true
    systemctl --user disable "$(basename "$inst")" >/dev/null 2>&1 || true
    rm -f "$inst"
    say "removed $(basename "$inst")"
  done
  systemctl --user daemon-reload 2>/dev/null || true
fi

# The fleet-start agent install.sh writes on macOS is not part of the loop above.
if [[ "$(uname -s)" == "Darwin" && -f "$PLIST_DIR/com.amux.fleet-start.plist" ]]; then
  launchctl bootout "gui/$UID_N/com.amux.fleet-start" 2>/dev/null || true
  rm -f "$PLIST_DIR/com.amux.fleet-start.plist"
  say "removed $PLIST_DIR/com.amux.fleet-start.plist"
fi

for b in amux-server-rs amux-rs amux; do
  if [[ -e "$BIN_DIR/$b" ]]; then
    rm -f "$BIN_DIR/$b"
    say "removed $BIN_DIR/$b"
  fi
done
if [[ -e "$BIN_DIR/scripts/amux-grid.sh" ]]; then
  rm -f "$BIN_DIR/scripts/amux-grid.sh"
  rmdir "$BIN_DIR/scripts" 2>/dev/null || true
  say "removed $BIN_DIR/scripts/amux-grid.sh"
fi
if [[ -e "$AMUX_HOME/bin/amux-build-authority" ]]; then
  rm -f "$AMUX_HOME/bin/amux-build-authority"
  say "removed $AMUX_HOME/bin/amux-build-authority"
fi

# The generated cargo config names an absolute path on THIS machine, so it is
# install output, not data.
if [[ -n "${AMUX_REPO_DIR:-}" && -f "$AMUX_REPO_DIR/.cargo/config.toml" ]] \
   && grep -q "GENERATED by install.sh" "$AMUX_REPO_DIR/.cargo/config.toml" 2>/dev/null; then
  rm -f "$AMUX_REPO_DIR/.cargo/config.toml"
  say "removed $AMUX_REPO_DIR/.cargo/config.toml"
fi

echo ""
warn "KEPT (on purpose): $AMUX_HOME — your DB, sessions, auth token, memory and logs."
echo "  Also kept: the amux hook entries in ~/.claude/settings.json (they name"
echo "  \$HOME/.amux/hook-report.sh and no-op once that file is gone; remove them by hand"
echo "  if you want them out), and this checkout."
echo "  amux never deletes your data on uninstall. Re-run ./install.sh to come back to it,"
echo "  or remove it yourself if you truly want a clean slate:  rm -rf $AMUX_HOME"
